/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import aiproject.Cs461;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author skerd
 */
public class LoadingPanel extends javax.swing.JPanel {

    public static boolean haveAllQuestions;
    public static ArrayList<Object> aaClues;
    public static ArrayList<Object> ddClues;
    
    public static ArrayList<Object> newDownClues;
    public static ArrayList<Object> newAccrossClues;
    
    public static ArrayList<Object> tiles;
    
    public LoadingPanel() {
        
        initComponents();


        new Thread(new Runnable() {
            public void run() {
                haveAllQuestions = false;
                int count = 1;

                while( !haveAllQuestions ){

                    if( count %3 == 0){
                        loadingLabel.setText("Loading.  ");
                    }
                    else if( count %3 == 1){
                        loadingLabel.setText("Loading.. ");
                    }
                    else{
                        loadingLabel.setText("Loading...");
                    }

                    count++;

                    try {
                        TimeUnit.MILLISECONDS.sleep((long) 500.0);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoadingPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                System.out.println(tiles.size() + " at loading panel !!!!!!!!!!!!!! ");
                System.out.println("Trying to switch panels!!!");
                Cs461.main.setCluesAndStartPuzzle( aaClues, ddClues, newAccrossClues, newDownClues,  tiles );
            
            }
        }).start();


    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loading questions from today's puzzle! ");

        loadingLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        loadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingLabel.setText("!");

        errorLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(loadingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loadingLabel;
    // End of variables declaration//GEN-END:variables
}
